In [45]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
# linspace takes in number of points you want as third argument while arange takes in steps as third argument

In [ ]:
# identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# creates an array of a shape passed in and populates it with random samples from a uniform distribution from 0 to 1

In [18]:
np.random.rand(5)

array([0.94646783, 0.22613574, 0.4604412 , 0.00100049, 0.61451587])

In [19]:
np.random.rand(5,5)

array([[0.48180103, 0.86478199, 0.82623612, 0.63288045, 0.69407763],
       [0.09957706, 0.51889961, 0.95479372, 0.22660218, 0.1006546 ],
       [0.32732253, 0.19525578, 0.70365946, 0.52301469, 0.63019309],
       [0.27108105, 0.79209467, 0.20860473, 0.45190686, 0.09057005],
       [0.60269296, 0.19601534, 0.01720958, 0.8144765 , 0.73906262]])

In [20]:
# return a sample from the standard normal distribution centered around 0

In [21]:
np.random.randn(5)

array([ 0.02073236, -0.44214379,  1.04274734,  1.37151729, -0.00530856])

In [22]:
np.random.randn(4,4)

array([[ 0.59691921, -1.02950559,  1.00791334, -0.31398087],
       [-0.80888027, -0.93355715,  1.08902724,  1.60084965],
       [ 0.53773514,  0.83922741,  0.94028706,  0.4571649 ],
       [ 0.78735382,  0.3937832 , -0.04446792,  0.62128932]])

In [23]:
np.random.randint(1,100)

25

In [29]:
np.random.randint(1,100,10)

array([35, 75, 66, 10, 81, 69, 24, 11, 15, 79])

In [ ]:
# reshape

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([38, 27, 23, 40, 43, 27, 17, 42, 19, 28])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
# max, min, and indexes

In [31]:
ranarr.max()

43

In [32]:
ranarr.min()

17

In [33]:
ranarr.argmax()

4

In [41]:
ranarr.argmin()

6

In [42]:
# shape of array

In [37]:
arr.shape

(25,)

In [39]:
arr = arr.reshape(5,5)

In [40]:
arr.shape

(5, 5)

In [43]:
# data type 

In [44]:
arr.dtype

dtype('int64')

In [46]:
from numpy.random import randint

In [47]:
randint(5)

3